name: Ansible Lint

on: 
  push:
    branches: 
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0
      env:
        ACTION_PLAYBOOK_NAME: playbook.yml
