- name: Ensure project path exist
  file:
    path: "{{ project_dest_path }}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755

- name: Ensure service script exist
  template:
    src: service.sh.j2
    dest: "{{ project_dest_path }}/service.sh"
    owner: tomcat
    group: tomcat
    mode: 0755

- name: Stop service
  shell: ./service.sh stop
  args:
    chdir: "{{ project_dest_path }}"
    executable: /bin/bash

- name: Wait service stop
  wait_for:
    host: 0.0.0.0
    port: "{{ project_port }}"
    delay: 5
    state: stopped
    timeout: 120

- name: Upload jar archive
  copy:
    src: "{{ archive_src_path }}/{{ archive_name }}"
    dest: "{{ project_dest_path }}/{{ archive_name }}"
    backup: "{{ project_archive_backup | default('no') }}"

- name: Start service
  shell: ./service.sh start
  args:
    chdir: "{{ project_dest_path }}"
    executable: /bin/bash

- name: Wait service start
  wait_for:
    host: 0.0.0.0
    port: "{{ project_port }}"
    delay: 10
    state: started
    timeout: 300
