# - name: Install epel-release
#   yum:
#     name: epel-release
#     state: present
#     update_cache: yes
  
- name: CentOS 7 install remi
  yum:  
    name: "https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/remi-release-7.rpm"
    state: present

- name: CentOS install PHP 7.1 and Extend
  yum:
    name:
      - php71-php-pear 
      - php71-php-cli 
      - php71-php-common 
      - php71-php-curl  
      - php71-php-devel 
      - php71-php-fpm 
      - php71-php-json 
      - php71-php-mbstring 
      - php71-php-mcrypt 
      - php71-php-mysql 
      - php71-php-opcache 
      - php71-php-zip 
      - php71-php-intl 
      - php71-php-gd 
      - php71-php-xml
    state: present

- name: Add config to php.ini
  lineinfile:
    dest: /etc/opt/remi/php71/php.ini
    line: "{{ php_vars }}"
    backup: yes
  notify: CentOS restart php
