- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: Add repository
  apt_repository:
    repo: ppa:ondrej/php

# - name: Add PHP key
#   apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: 4F4EA0AAE5267A6C

- name: Ubuntu install PHP 7.1
  apt:
    name: 
      - php-pear
      - php7.1-cli
      - php7.1-common
      - php7.1-curl
      - php7.1-dev
      - php7.1-fpm
      - php7.1-json
      - php7.1-mbstring
      - php7.1-mcrypt
      - php7.1-mysql
      - php7.1-opcache
      - php7.1-zip
      - php7.1-intl
      - php7.1-gd
      - php7.1-xml

- name: Add config to php.ini
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    line: "{{ php_vars }}"
    backup: yes
  notify: Ubuntu restart php