---

- name: Add vhost
  template:
    src: vhost.j2
    dest: "{{ nginx_vhost_path }}/{{ item.filename }}"
    owner: "{{ nginx_user }}"
    mode: 0644
  when: item.state|default('present') != 'absent'
  with_items: "{{ nginx_vhost }}"
  notify: reload nginx

- name: Delete vhost
  file:
    path: "{{ nginx_vhost_path }}/{{ item.filename }}"
    state: absent
  when: item.state|default('present') == "absent"
  with_items: "{{ nginx_vhost }}"
  notify: reload nginx
