---

- name: Disable selinux
  selinux:
    policy: targeted
    state: permissive

- name: Add mysql communtity repository
  yum:
    name: "{{ mysql_community_repository }}"
    state: present

# 修改为国内中科大下载源
- name: Modify mysql communtity
  replace:
    path: /etc/yum.repos.d/mysql-community.repo
    regexp: "^(.*)http://repo.mysql.com/yum/mysql-5.6-community/el/7/$basearch/"
    replace: '\1https://mirrors.tuna.tsinghua.edu.cn/mysql/yum/mysql57-community-el7'
    backup: yes

# 中科大的最新版为 5.7.25
# 191118 最新版为 5.7.27
# 换清华源
- name: Install mysql
  yum:
    name:
      #- mysql-community-libs-5.7.25 
      #- mysql-community-common-5.7.25 
      #- mysql-community-libs-compat-5.7.25 
      #- mysql-community-server-5.7.25 
      #- mysql-community-client-5.7.25
      - mysql-community-server
      - mysql-community-client
    state: present
    update_cache: yes
