---

# - name: Download Tomcat 9
#   get_url:
#     url: "{{ tomcat_download_url }}"
#     dest: /tmp/tomcat9.tgz
#   connection: local
#   run_once: yes

- name: Ensure tomcat user exists
  user:
    name: tomcat
    state: present

- name: Ensure tomcat path exists
  file:
    path: "{{ tomcat_basedir }}"
    state: directory
    owner: "{{ tomcat_user }}"

- name: Upload tomcat
  unarchive:
    src: "{{ tomcat_download_url }}"
    dest: "{{ tomcat_basedir }}"
    owner: "{{ tomcat_user }}"
    remote_src: yes
    creates: "{{ tomcat_path }}"

- name: Add tomcat configure
  template:
    src: server.xml.j2
    dest: "{{ tomcat_path }}/conf/server.xml"
    owner: "{{ tomcat_user }}"
    backup: yes

- name: Add tomcat service
  template:
    src: tomcat.service.j2
    dest: /lib/systemd/system/tomcat.service
  #notify: start tomcat
