---

- name: Add mysql.cnf
  template:
    src: mysql.cnf.j2
    dest: /etc/mysql/conf.d/mysql.cnf
    mode: 0644
    backup: yes
  notify: restart mysql

- name: Add client.cnf
  template:
    src: client.cnf.j2
    dest: /etc/mysql/conf.d/client.cnf
    mode: 0644
    backup: yes
  notify: restart mysql

- name: Add mysqld.cnf
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: 0644
    force: yes
    backup: yes
  notify: restart mysql
