---

- include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: setup-Redhat.yml
  when: ansible_os_family == "RedHat"

- name: Fix CentOS 8 "requires containerd.io" error
  yum:
    name: "{{ docker_containerd_io }}"
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: Install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure directory /etc/docker excist
  file:
    path: /etc/docker
    state: directory

- name: Add docker registry mirrors
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    backup: yes
  notify: restart docker

- name: Ensure docker is restarted
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool
