---

- name: Ensure old docker is removed
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Ensure dependencies is install
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
    update_cache: yes

- name: Add docker repository
  get_url:
    url: "{{ docker_yum_repository }}"
    dest: /etc/yum.repos.d/docker-ce.repo
