---

- name: Include OS variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure centos7 epel is enabled
  yum:
    name: epel-release
    state: present
    update_cache: yes
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Ensure redis is installed
  package:
    name: "{{ Redis_pkg_name }}"
    state: present
    update_cache: yes

- name: Redis Configure
  template:
    src: redis.conf.j2
    dest: "{{ Redis_conf_path }}"
  notify: restart redis
